require('dotenv').config();
const basePath = process.cwd();
const fs = require("fs");
const { MODE } = require(`${basePath}/constants/blend_mode.js`);
const { NETWORK } = require(`${basePath}/constants/network.js`);

const network = NETWORK.eth;

// General metadata for Ethereum
const namePrefix = "Mysterious Sprite Vendor";
const description = "Hand drawn sprite collection";
const baseUri = "ipfs://NewUriToReplace"; // This will be replaced automatically

const layerConfigurations = [
  // normal fairskin
  {
    growEditionSizeTo: 353,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair blonde" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears fair"},
      { name: "front hair blonde"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 706,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair blossom" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears fair"},
      { name: "front hair blossom"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 1059,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair sky blue" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears fair"},
      { name: "front hair sky blue"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 1412,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair scarlet" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears fair"},
      { name: "front hair scarlet"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 1765,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair white" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears fair"},
      { name: "front hair white"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 2118,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair byzantium" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears fair"},
      { name: "front hair byzantium"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 2471,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair space blue" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears fair"},
      { name: "front hair space blue"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 2824,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair matcha" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears fair"},
      { name: "front hair matcha"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 3177,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair brown" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears fair"},
      { name: "front hair brown"},
      { name: "bottle jar"},
    ],
  },
  {
    growEditionSizeTo: 3530,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair cream" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears fair"},
      { name: "front hair cream"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 3883,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair pumpkin" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears fair"},
      { name: "front hair pumpkin"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 4236,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair amethyst" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears fair"},
      { name: "front hair amethyst"},
      { name: "bottle jar"},
    ],
  },
  // normal darkskin
  {
    
    growEditionSizeTo: 4589,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair blonde" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears dark"},
      { name: "front hair blonde"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 4942,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair blossom" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears dark"},
      { name: "front hair blossom"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 5295,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair sky blue" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears dark"},
      { name: "front hair sky blue"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 5648,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair scarlet" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears dark"},
      { name: "front hair scarlet"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 6001,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair white" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears dark"},
      { name: "front hair white"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 6354,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair byzantium" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint fair"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears dark"},
      { name: "front hair byzantium"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 6707,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair space blue" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears dark"},
      { name: "front hair space blue"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 7060,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair matcha" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears dark"},
      { name: "front hair matcha"},
      { name: "bottle jar"},
    ],
  },
  {
    growEditionSizeTo: 7413,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair brown" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears dark"},
      { name: "front hair brown"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 7766,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair cream" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears dark"},
      { name: "front hair cream"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 8119,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair pumpkin" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears dark"},
      { name: "front hair pumpkin"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 8472,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "wings" },
      { name: "back hair amethyst" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark"},
      { name: "mouth"},
      { name: "eyes"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "head side accessory"},
      { name: "elf ears dark"},
      { name: "front hair amethyst"},
      { name: "bottle jar"},
    ],
  },
  // cat fairskin
  {
    growEditionSizeTo: 8514,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail blonde"},
      { name: "wings" },
      { name: "back hair blonde" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears blonde"},
      { name: "elf ears fair"},
      { name: "front hair blonde"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 8556,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail blossom"},
      { name: "wings" },
      { name: "back hair blossom" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears blossom"},
      { name: "elf ears fair"},
      { name: "front hair blossom"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 8598,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail sky blue"},
      { name: "wings" },
      { name: "back hair sky blue" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears sky blue"},
      { name: "elf ears fair"},
      { name: "front hair sky blue"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 8640,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail scarlet"},
      { name: "wings" },
      { name: "back hair scarlet" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears scarlet"},
      { name: "elf ears fair"},
      { name: "front hair scarlet"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 8682,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail white"},
      { name: "wings" },
      { name: "back hair white" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears white"},
      { name: "elf ears fair"},
      { name: "front hair white"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 8724,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail byzantium"},
      { name: "wings" },
      { name: "back hair byzantium" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears byzantium"},
      { name: "elf ears fair"},
      { name: "front hair byzantium"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 8766,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail space blue"},
      { name: "wings" },
      { name: "back hair space blue" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears space blue"},
      { name: "elf ears fair"},
      { name: "front hair space blue"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 8808,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail matcha"},
      { name: "wings" },
      { name: "back hair matcha" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears matcha"},
      { name: "elf ears fair"},
      { name: "front hair matcha"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 8850,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail brown"},
      { name: "wings" },
      { name: "back hair brown" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears brown"},
      { name: "elf ears fair"},
      { name: "front hair brown"},
      { name: "bottle jar"},
    ],
  },
  {
    growEditionSizeTo: 8892,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail cream"},
      { name: "wings" },
      { name: "back hair cream" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears cream"},
      { name: "elf ears fair"},
      { name: "front hair cream"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 8934,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail pumpkin"},
      { name: "wings" },
      { name: "back hair pumpkin" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears pumpkin"},
      { name: "elf ears fair"},
      { name: "front hair pumpkin"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 8976,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail amethyst"},
      { name: "wings" },
      { name: "back hair amethyst" },
      { name: "head fair" },
      { name: "costume fair" },
      { name: "blushes fair" },
      { name: "face paint fair c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears amethyst"},
      { name: "elf ears fair"},
      { name: "front hair amethyst"},
      { name: "bottle jar"},
    ],
  },
  // cat darkskin
  {
    growEditionSizeTo: 9018,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail blonde"},
      { name: "wings" },
      { name: "back hair blonde" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears blonde"},
      { name: "elf ears dark"},
      { name: "front hair blonde"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9060,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail blossom"},
      { name: "wings" },
      { name: "back hair blossom" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears blossom"},
      { name: "elf ears dark"},
      { name: "front hair blossom"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9102,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail sky blue"},
      { name: "wings" },
      { name: "back hair sky blue" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears sky blue"},
      { name: "elf ears dark"},
      { name: "front hair sky blue"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9144,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail scarlet"},
      { name: "wings" },
      { name: "back hair scarlet" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears scarlet"},
      { name: "elf ears dark"},
      { name: "front hair scarlet"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9186,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail white"},
      { name: "wings" },
      { name: "back hair white" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears white"},
      { name: "elf ears dark"},
      { name: "front hair white"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9228,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail byzantium"},
      { name: "wings" },
      { name: "back hair byzantium" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears byzantium"},
      { name: "elf ears dark"},
      { name: "front hair byzantium"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9270,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail space blue"},
      { name: "wings" },
      { name: "back hair space blue" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears space blue"},
      { name: "elf ears dark"},
      { name: "front hair space blue"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9312,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail matcha"},
      { name: "wings" },
      { name: "back hair matcha" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears matcha"},
      { name: "elf ears dark"},
      { name: "front hair matcha"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9354,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail brown"},
      { name: "wings" },
      { name: "back hair brown" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears brown"},
      { name: "elf ears dark"},
      { name: "front hair brown"},
      { name: "bottle jar"},
    ],
  },
  {
    growEditionSizeTo: 9396,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail cream"},
      { name: "wings" },
      { name: "back hair cream" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears cream"},
      { name: "elf ears dark"},
      { name: "front hair cream"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9438,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail pumpkin"},
      { name: "wings" },
      { name: "back hair pumpkin" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears pumpkin"},
      { name: "elf ears dark"},
      { name: "front hair pumpkin"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9480,
    layersOrder: [
      { name: "background" },
      { name: "effect" },
      { name: "cat tail amethyst"},
      { name: "wings" },
      { name: "back hair amethyst" },
      { name: "head dark" },
      { name: "costume dark" },
      { name: "blushes dark" },
      { name: "face paint dark c"},
      { name: "mouth"},
      { name: "eyes c"},
      { name: "brows"},
      { name: "head top accessory"},
      { name: "cat ears amethyst"},
      { name: "elf ears dark"},
      { name: "front hair amethyst"},
      { name: "bottle jar"},
    ],
  },
  // monster fairskin
  {
    growEditionSizeTo: 9501,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair blonde" },
      { name: "head fair" },
      { name: "costume fair m" },
      { name: "blushes fair" },
      { name: "face paint fair m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears fair m"},
      { name: "front hair blonde"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9522,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair blossom" },
      { name: "head fair" },
      { name: "costume fair m" },
      { name: "blushes fair" },
      { name: "face paint fair m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears fair m"},
      { name: "front hair blossom"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9543,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair sky blue" },
      { name: "head fair" },
      { name: "costume fair m" },
      { name: "blushes fair" },
      { name: "face paint fair m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears fair m"},
      { name: "front hair sky blue"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9564,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair scarlet" },
      { name: "head fair" },
      { name: "costume fair m" },
      { name: "blushes fair" },
      { name: "face paint fair m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears fair m"},
      { name: "front hair scarlet"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9585,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair white" },
      { name: "head fair" },
      { name: "costume fair m" },
      { name: "blushes fair" },
      { name: "face paint fair m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears fair m"},
      { name: "front hair white"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9606,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair byzantium" },
      { name: "head fair" },
      { name: "costume fair m" },
      { name: "blushes fair" },
      { name: "face paint fair m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears fair m"},
      { name: "front hair byzantium"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9627,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair space blue" },
      { name: "head fair" },
      { name: "costume fair m" },
      { name: "blushes fair" },
      { name: "face paint fair m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears fair m"},
      { name: "front hair space blue"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9648,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair matcha" },
      { name: "head fair" },
      { name: "costume fair m" },
      { name: "blushes fair" },
      { name: "face paint fair m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears fair m"},
      { name: "front hair matcha"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9669,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair brown" },
      { name: "head fair" },
      { name: "costume fair m" },
      { name: "blushes fair" },
      { name: "face paint fair m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears fair m"},
      { name: "front hair brown"},
      { name: "bottle jar"},
    ],
  },
  {
    growEditionSizeTo: 9690,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair cream" },
      { name: "head fair" },
      { name: "costume fair m" },
      { name: "blushes fair" },
      { name: "face paint fair m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears fair m"},
      { name: "front hair cream"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9711,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair pumpkin" },
      { name: "head fair" },
      { name: "costume fair m" },
      { name: "blushes fair" },
      { name: "face paint fair m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears fair m"},
      { name: "front hair pumpkin"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9732,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair amethyst" },
      { name: "head fair" },
      { name: "costume fair m" },
      { name: "blushes fair" },
      { name: "face paint fair m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears fair m"},
      { name: "front hair amethyst"},
      { name: "bottle jar"},
    ],
  },
  // monster darkskin
  {
    growEditionSizeTo: 9753,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair blonde" },
      { name: "head dark" },
      { name: "costume dark m" },
      { name: "blushes dark" },
      { name: "face paint dark m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears dark m"},
      { name: "front hair blonde"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9774,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair blossom" },
      { name: "head dark" },
      { name: "costume dark m" },
      { name: "blushes dark" },
      { name: "face paint dark m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears dark m"},
      { name: "front hair blossom"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9795,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair sky blue" },
      { name: "head dark" },
      { name: "costume dark m" },
      { name: "blushes dark" },
      { name: "face paint dark m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears dark m"},
      { name: "front hair sky blue"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9816,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair scarlet" },
      { name: "head dark" },
      { name: "costume dark m" },
      { name: "blushes dark" },
      { name: "face paint dark m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears dark m"},
      { name: "front hair scarlet"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9837,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair white" },
      { name: "head dark" },
      { name: "costume dark m" },
      { name: "blushes dark" },
      { name: "face paint dark m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears dark m"},
      { name: "front hair white"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9858,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair byzantium" },
      { name: "head dark" },
      { name: "costume dark m" },
      { name: "blushes dark" },
      { name: "face paint dark m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears dark m"},
      { name: "front hair byzantium"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9879,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair space blue" },
      { name: "head dark" },
      { name: "costume dark m" },
      { name: "blushes dark" },
      { name: "face paint dark m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears dark m"},
      { name: "front hair space blue"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9900,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair matcha" },
      { name: "head dark" },
      { name: "costume dark m" },
      { name: "blushes dark" },
      { name: "face paint dark m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears dark m"},
      { name: "front hair matcha"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9921,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair brown" },
      { name: "head dark" },
      { name: "costume dark m" },
      { name: "blushes dark" },
      { name: "face paint dark m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears dark m"},
      { name: "front hair brown"},
      { name: "bottle jar"},
    ],
  },
  {
    growEditionSizeTo: 9942,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair cream" },
      { name: "head dark" },
      { name: "costume dark m" },
      { name: "blushes dark" },
      { name: "face paint dark m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears dark m"},
      { name: "front hair cream"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9963,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair pumpkin" },
      { name: "head dark" },
      { name: "costume dark m" },
      { name: "blushes dark" },
      { name: "face paint dark m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears dark m"},
      { name: "front hair pumpkin"},
      { name: "bottle jar"},
    ],
  },
  {  
    growEditionSizeTo: 9984,
    layersOrder: [
      { name: "background" },
      { name: "effect m" },
      { name: "wings m" },
      { name: "back hair amethyst" },
      { name: "head dark" },
      { name: "costume dark m" },
      { name: "blushes dark" },
      { name: "face paint dark m"},
      { name: "mouth"},
      { name: "eyes m"},
      { name: "brows"},
      { name: "head top accessory m"},
      { name: "head side accessory m"},
      { name: "elf ears dark m"},
      { name: "front hair amethyst"},
      { name: "bottle jar"},
    ],
  },
];

const shuffleLayerConfigurations = true;

const debugLogs = false;

const format = {
  width: 2362,
  height: 2362,
  smoothing: false,
};

const extraMetadata = {
  external_url: "", // Replace with your website or remove this line if you do not have one.
};

// NFTPort Info

// ** REQUIRED **
const AUTH = process.env.NFTPORT_API_KEY; // Set this in the .env file to prevent exposing your API key when pushing to Github
const LIMIT = 2; // Your API key rate limit
const CHAIN = 'rinkeby'; // only rinkeby, polygon, or ethereum

// REQUIRED CONTRACT DETAILS THAT CANNOT BE UPDATED LATER!
const CONTRACT_NAME = 'Mysterious Sprite Vendor';
const CONTRACT_SYMBOL = 'MSV';
const METADATA_UPDATABLE = true; // set to false if you don't want to allow metadata updates after minting
const OWNER_ADDRESS = '0xe13989735308B63Dd06C9909dF78Fe56325a6c77';
const TREASURY_ADDRESS = '0xe13989735308B63Dd06C9909dF78Fe56325a6c77';
const MAX_SUPPLY = 9984; // The maximum number of NFTs that can be minted. CANNOT BE UPDATED!
const MINT_PRICE = 0.001; // Minting price per NFT. Rinkeby = ETH, Ethereum = ETH, Polygon = MATIC. CANNOT BE UPDATED!
const TOKENS_PER_MINT = 10; // maximum number of NFTs a user can mint in a single transaction. CANNOT BE UPDATED!

// REQUIRED CONTRACT DETAILS THAT CAN BE UPDATED LATER.
const PUBLIC_MINT_START_DATE = "2022-09-30T11:30:48+09:00"; // This is required. Eg: 2022-02-08T11:30:48+00:00

// OPTIONAL CONTRACT DETAILS THAT CAN BE UPDATED LATER.
const PRESALE_MINT_START_DATE = null; // Optional. Eg: 2022-02-08T11:30:48+00:00
const ROYALTY_SHARE = 1000; // Percentage of the token price that goes to the royalty address. 100 bps = 1%
const ROYALTY_ADDRESS = "0xe13989735308B63Dd06C9909dF78Fe56325a6c77"; // Address that will receive the royalty
const BASE_URI = null; // only update if you want to manually set the base uri
const PREREVEAL_TOKEN_URI = null; // only update if you want to manually set the prereveal token uri
const PRESALE_WHITELISTED_ADDRESSES = ["0xe13989735308B63Dd06C9909dF78Fe56325a6c77"]; // only update if you want to manually set the whitelisted addresses

// ** OPTIONAL **
let CONTRACT_ADDRESS = "YOUR CONTRACT ADDRESS"; // If you want to manually include it

// Generic Metadata is optional if you want to reveal your NFTs
const GENERIC = true; // Set to true if you want to upload generic metas and reveal the real NFTs in the future
const GENERIC_TITLE = CONTRACT_NAME; // Replace with what you want the generic titles to say if you want it to be different from the contract name.
const GENERIC_DESCRIPTION = "Summoning sprite..."; // Replace with what you want the generic descriptions to say.
const GENERIC_IMAGE = "https://ipfs.io/ipfs/bafybeic6zu25ssq3m5hzla3vcmppercqvzbahpfgcgikrosdujb6hhmojy"; // Replace with your generic image that will display for all NFTs pre-reveal.

// Automatically set contract address if deployed using the deployContract.js script
try {
  const rawContractData = fs.readFileSync(
    `${basePath}/build/contract/_contract.json`
  );
  const contractData = JSON.parse(rawContractData);
  if (contractData.response === "OK") {
    CONTRACT_ADDRESS = contractData.contract_address;
  }
} catch (error) {
  // Do nothing, falling back to manual contract address
}
// END NFTPort Info

const solanaMetadata = {
  symbol: "YC",
  seller_fee_basis_points: 1000, // Define how much % you want from secondary market sales 1000 = 10%
  external_url: "https://www.youtube.com/c/hashlipsnft",
  creators: [
    {
      address: "7fXNuer5sbZtaTEPhtJ5g5gNtuyRoKkvxdjEjEnPN4mC",
      share: 100,
    },
  ],
};

const gif = {
  export: false,
  repeat: 0,
  quality: 100,
  delay: 500,
};

const text = {
  only: false,
  color: "#ffffff",
  size: 20,
  xGap: 40,
  yGap: 40,
  align: "left",
  baseline: "top",
  weight: "regular",
  family: "Courier",
  spacer: " => ",
};

const pixelFormat = {
  ratio: 2 / 128,
};

const background = {
  generate: false,
  brightness: "80%",
  static: false,
  default: "#000000",
};

const rarityDelimiter = "#";

const uniqueDnaTorrance = 10000;

const preview = {
  thumbPerRow: 5,
  thumbWidth: 50,
  imageRatio: format.height / format.width,
  imageName: "preview.png",
};

const preview_gif = {
  numberOfImages: 5,
  order: "ASC", // ASC, DESC, MIXED
  repeat: 0,
  quality: 100,
  delay: 500,
  imageName: "preview.gif",
};

module.exports = {
  format,
  baseUri,
  description,
  background,
  uniqueDnaTorrance,
  layerConfigurations,
  rarityDelimiter,
  preview,
  shuffleLayerConfigurations,
  debugLogs,
  extraMetadata,
  pixelFormat,
  text,
  namePrefix,
  network,
  solanaMetadata,
  gif,
  preview_gif,
  AUTH,
  LIMIT,
  CONTRACT_ADDRESS,
  OWNER_ADDRESS,
  TREASURY_ADDRESS,
  CHAIN,
  GENERIC,
  GENERIC_TITLE,
  GENERIC_DESCRIPTION,
  GENERIC_IMAGE,
  CONTRACT_NAME,
  CONTRACT_SYMBOL,
  METADATA_UPDATABLE,
  ROYALTY_SHARE,
  ROYALTY_ADDRESS,
  MAX_SUPPLY,
  MINT_PRICE,
  TOKENS_PER_MINT,
  PRESALE_MINT_START_DATE,
  PUBLIC_MINT_START_DATE,
  BASE_URI,
  PREREVEAL_TOKEN_URI,
  PRESALE_WHITELISTED_ADDRESSES
};
